version: '3'

volumes:
  postgres-data:

services:
  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=codeedu
    ports:
      - "5432:5432"